variable "instance_type" {}
variable "ami_image" {}
variable "public_subnet" {}
variable "private_subnet" {}
variable "key_name_1" {}
variable "vpc_id" {}
variable "project_sec_grp" {}
variable "project_sec_grp2" {}
variable "key_name_2" {}